/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PsTareasCalificadasJpaController;
import controller.PsTareasJpaController;
import controller.PsUsuariosJpaController;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.PsTareas;
import model.PsUsuarios;

/**
 *
 * @author Juan Camilo Giron
 */
public final class MDIApplication extends javax.swing.JFrame {

    //Declarando JinternalFrames
    LoginJInternalFrame loginJInternalFrame;
    MainJInternalFrame mainJInternalFrame;
    RegistroJInternalFrame registroJInternalFrame;
    TareaJInternalFrame tareaJInternalFrame;

    //Declarando controladores Jpa
    PsTareasJpaController ctrlPsTareasJpaController;
    PsTareasCalificadasJpaController ctrlPsTareasCalificadasJpaController;
    PsUsuariosJpaController ctrlUsuariosJpaController;

    //Obtener el ancho de la pantalla para el jPanel que contiene los botones del crud 
    Toolkit tk = Toolkit.getDefaultToolkit();
    int xSize = ((int) tk.getScreenSize().getWidth());

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        //Se einicializa los JpaController
        ctrlPsTareasJpaController = new PsTareasJpaController();
        ctrlPsTareasCalificadasJpaController = new PsTareasCalificadasJpaController();
        ctrlUsuariosJpaController = new PsUsuariosJpaController();
        
        //Se Inicia el tamaño del MDI de acuerdo a la resolucion de la pantalla 
        this.setExtendedState(MDIApplication.MAXIMIZED_BOTH);
        jPanelTooblar.setSize(xSize, 50);
        jPanelTooblar.setVisible(true);
        getViewLogin();
    }

    public void getViewLogin() {

        loginJInternalFrame = new LoginJInternalFrame();
        desktopPane.add(loginJInternalFrame);
        loginJInternalFrame.setVisible(true);

        try {
            loginJInternalFrame.setMaximum(true);
            loginJInternalFrame.setLocation(0, 50);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(MDIApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanelTooblar = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save-icon.png"))); // NOI18N
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit-icon.png"))); // NOI18N
        editButton.setFocusable(false);
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(editButton);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete-icon.png"))); // NOI18N
        deleteButton.setFocusable(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(deleteButton);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search-icon.png"))); // NOI18N
        searchButton.setFocusable(false);
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(searchButton);

        javax.swing.GroupLayout jPanelTooblarLayout = new javax.swing.GroupLayout(jPanelTooblar);
        jPanelTooblar.setLayout(jPanelTooblarLayout);
        jPanelTooblarLayout.setHorizontalGroup(
            jPanelTooblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanelTooblarLayout.setVerticalGroup(
            jPanelTooblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        desktopPane.add(jPanelTooblar);
        jPanelTooblar.setBounds(0, 0, 400, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        Object object = null;

        try {
            object = interfaceCrear((InterfaceCRUD) desktopPane.getSelectedFrame());
        } catch (NullPointerException e) {
            System.out.println("NullpointerException+ Err" + object);
        }

        if (object != null) {
            if (object instanceof PsUsuarios) {

                PsUsuarios psUsuarios = (PsUsuarios) object;
                ctrlUsuariosJpaController.create(psUsuarios);
                            
                JOptionPane.showMessageDialog(null, "El usuario ha sido creado satifactoriamente");
                
            }else if (object instanceof PsTareas) {
               
                PsTareas psTareas=(PsTareas)object;
                ctrlPsTareasJpaController.create(psTareas);
                
                JOptionPane.showMessageDialog(null, "La tarea ha sido creada satisfactoriamente");
                
            }
        }


    }//GEN-LAST:event_saveButtonActionPerformed
    public Object interfaceCrear(InterfaceCRUD interfaceCRUD) {
        return interfaceCRUD.save();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanelTooblar;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

}
